### ISSUE TITLE
How to use rtail on android phone?

### ISSUE THREAD

**Issue by ghost** [kilianc/rtail#103]
Is there any way to see `rtail` using smartphone?

I had established ssh connection to laptop via android ssh-client `connectbot`, but page still is not loadable.

Can someone help?

**Comment by kilianc** [comment]
@a93ushakov not sure I understand what you are trying to do and why you are mentioning `ssh` from your phone.

In order to reach rtail webapp just type the webapp url on your smartphone. If it's running on localhost be sure to use `--web-host 0.0.0.0` and access the interface with you `LAN` ip address.

Just to be clear, rtail is not supported on mobile devices
