### ISSUE TITLE
rtail doesn't handle newlines well

### ISSUE THREAD

**Issue by oldgregg-zz** [kilianc/rtail#105]
Hello! I'm using rtail for some logging, and sometimes the logs I send to it are multi-line (as in the event of a python exception + traceback). Right now, the lines get stuffed into the single line, and overlap one another. Is there a method to instead show the first line w/ timestamp, then subsequent lines? keeping them in the same "record" is alright. Thanks!

**Comment by kilianc** [comment]
@oldgregg thanks for giving rtail a try.

rtail only understands newline separated logs, which is pretty standard. What you describe seems like a bug because at least you should be able to see each line of your stack trace as separate like, the goal is to have 1:1 with the terminal.

Could you send me a screenshot? If it contains sensitive data just send me an email or a tweet.

**Comment by oldgregg-zz** [comment]
@kilianc - I just came back to let you know this is not a bug - it was an error with the way I was dumping the python exceptions. Sorry to get you spun up!

However, I do think there might be some value in wrapping lines that are "too long", so you don't get a left/right scrollbar. Your thoughts? If I get a few free cycles and can test it, I'll submit a pull request.
