### ISSUE TITLE
Fonts are too small

### ISSUE THREAD

**Issue by kaihendry** [kilianc/rtail#67]
Even when adjusted up in the UI.

<img src=http://s.natalian.org/2015-07-09/1436429706_1918x1058.png>

I can't quite figure out which CSS I should attempt to override. Your CSS is quite overly complex. Also, would be nice to have wrapping so I read long lines without interacting with the browser!

**Comment by kilianc** [comment]
Lines shouldn't soft-wrap, is part of the deal when dealing with log files. But I understand why you want to do it for your use case, let me think how we can fix this.

That said, to make the font bigger you need to change the `.font-size-7` rule to whatever you want.

The CSS is compiled from SASS, that's why is not human friendly, I can assure you it makes sense: https://github.com/kilianc/rtail/blob/develop/app/scss/_fonts.scss

**Comment by kilianc** [comment]
If you fork this I'll be happy to PR on your work, meanwhile I am gonna close this!
Thanks for stopping by ;)

**Comment by kaihendry** [comment]
What are the steps to have my own user modifications to your style sheet? I.e. remove sidebar? Fork it? https://youtu.be/Xr1UzmNH3GU
